### ISSUE TITLE
How to use with rich-markdown-editor?

### ISSUE THREAD

**Issue by Shawnxkwang** [joelewis/prosemirror-mentions#19]
prosemirror-mentions doesn't seem to be usable with https://github.com/outline/rich-markdown-editor. I might be wrong, but seems prosemirror-mentions and official plugins has different props.

**Comment by Shawnxkwang** [comment]
figured out it's https://github.com/outline/rich-markdown-editor 's bug. closing this ticket

**Comment by tony** [comment]
@Shawnxkwang was there any additional effort / config in setting up [prosemirror-mentions](https://github.com/joelewis/prosemirror-mentions) with rich-markdown-editor?

(I came here from google search)

**Comment by tony** [comment]
Related: https://github.com/joelewis/prosemirror-mentions/issues/17 prosemirror-mentions with markdown

**Comment by tony** [comment]
@Shawnxkwang If there was a bug in rich-markdown-editor, can you link it?
