### ISSUE TITLE
Position issue for suggestion-item-list

### ISSUE THREAD

**Issue by yogen-darji-hs** [joelewis/prosemirror-mentions#27]
If Editor is inside any div, position is not calculated correctly for suggestion list.

Here is demo to how it looks like.
https://stackblitz.com/edit/react-gvo8kk

Is there any workaround to resolve it?

**Comment by yogen-darji-hs** [comment]
I found it was issue from my end in @progress/kendo-react-editor

**Comment by sdaly** [comment]
I was encountering the same issue with this & the Kendo React Editor. The fix was to change `defaultEditMode` to `div` from the default `iframe`. 

<img width="209" height="55" alt="Image" src="https://github.com/user-attachments/assets/d41325c9-3b14-4df7-bc96-0a530e14536b" />
