### ISSUE TITLE
dispatchTransaction not called when selection a mention

### ISSUE THREAD

**Issue by gdelory** [joelewis/prosemirror-mentions#29]
Hi, I noticed that selecting a mention doesn't call [dispatchTransaction](https://prosemirror.net/docs/ref/#view.DirectEditorProps.dispatchTransaction), which breaks react-prosemirror since it relies on this to update the state.

As a result as long no other input is done (press a key like space or use a command), the state of the document is invalid. In our case saving the text saved the text without the mention (plain text typed for the search)

I think [this line](https://github.com/joelewis/prosemirror-mentions/blob/e0e77289de18462ea08f290f25b545a141f76f59/src/mentionPlugin.js#L246) should be a `view.dispatch` instead of `view.updateState`, which does trigger the `updateState` eventually according to [the doc](https://prosemirror.net/docs/ref/#view.EditorView.dispatch), but also will call [dispatchTransation ](https://prosemirror.net/docs/ref/#view.DirectEditorProps.dispatchTransaction) which is important for many plugins.

I'm not a prosemirror expert so I hope this wouldn't break anything.

**Comment by ravi7mech** [comment]
Hi @gdelory This issue is valid and I have made some changes based on your analyis and it is working [Merge Request](https://github.com/joelewis/prosemirror-mentions/pull/30)

**Comment by gdelory** [comment]
Thanks a lot @ravi7mech!!! I added [a comment](https://github.com/joelewis/prosemirror-mentions/pull/30#issuecomment-978107920) on the PR

**Comment by joelewis** [comment]
Thanks for the patch #30 . Closing the issue now.

**Comment by gdelory** [comment]
For the record, issue fixed in 1.0.2 on npmjs.org, thank you so much @joelewis for your reactivity, highly appreciated!
